version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tirth@2005
      POSTGRES_DB: Odoo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    restart: always
    environment:
      PGUSER: postgres
      PGPASSWORD: Tirth@2005
      PGDATABASE: Odoo
      PGHOST: db
      PGPORT: 5432
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  db_data: